apiVersion: apps/v1
kind: Deployment
metadata:
  name: inscripcion-empleador-deployment
spec:
  replicas: 1  # Cambia este valor según tus necesidades de escalabilidad
  selector:
    matchLabels:
      app: inscripcion-empleador
  template:
    metadata:
      labels:
        app: inscripcion-empleador
    spec:
      hostAliases:                   # Agregamos la sección de hostAliases aquí
      - ip: "34.171.241.56"
        hostnames:
        - "kafka-svc"
      containers:
      - name: inscripcion-empleador
        image: johnmejia9887654321/incripcion-empleador-v5:latest  # Utiliza tu imagen Docker desde Docker Hub
        ports:
        - containerPort: 8081

---
apiVersion: v1
kind: Service
metadata:
  name: inscripcion-empleador-service
spec:
  selector:
    app: inscripcion-empleador
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8081
  type: LoadBalancer  # Cambio aquí para utilizar NodePort
