version: '3'
services:
  springboot-app:
    ports:
      - 8080:8080
    build:
      context: .
      args:
        JAR_FILE: /GenerateAutomaticId-0.0.1-SNAPSHOT.jar
    restart: always

    extra_hosts:
      - "cassandra-svc:172.20.144.1"